stage: "development"
service_version: "0.0.1"

http:
  host: "0.0.0.0"
  port: "8081"
  read_header_timeout: "5s"
  read_timeout: "15s"
  write_timeout: "15s"
  idle_timeout: "60s"

logger:
  level: "info"

pg:
  host: "localhost"
  port: "5432"
  database: "order-service"
  user: "order-service-user"
  password: "order-service-password"
  sslmode: "disable"

kafka:
  brokers:
    - "localhost:9092"

order_paid_producer:
  topic: "order.paid"

ship_assembled_consumer_config:
  topic: "ship.assembled"
  group: "order-service"

inventory_client:
  address: "localhost:50051"
  keepalive_time: "60s"
  keepalive_timeout: "20s"
  permit_without_stream: true

payment_client:
  address: "localhost:50052"
  keepalive_time: "60s"
  keepalive_timeout: "20s"
  permit_without_stream: true

iam_client:
  address: "localhost:50053"
  keepalive_time: "60s"
  keepalive_timeout: "20s"
  permit_without_stream: true

shutdown_config:
  shutdown_timeout: "10s"

otel:
  endpoint: "localhost:4317"
  service_name: "order-service"

tracing_config:
  sampling_ratio: 1.0