// Code generated for FOCCms service
// © FOCCms 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/FOCCms/go-microservices-course/inventory/internal/model/entity"
	"github.com/FOCCms/go-microservices-course/inventory/internal/model/valueobject"
	mock "github.com/stretchr/testify/mock"
)

// NewPartService creates a new instance of PartService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPartService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PartService {
	mock := &PartService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PartService is an autogenerated mock type for the PartService type
type PartService struct {
	mock.Mock
}

type PartService_Expecter struct {
	mock *mock.Mock
}

func (_m *PartService) EXPECT() *PartService_Expecter {
	return &PartService_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function for the type PartService
func (_mock *PartService) Commit(ctx context.Context, uuids []string) error {
	ret := _mock.Called(ctx, uuids)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = returnFunc(ctx, uuids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PartService_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type PartService_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
//   - uuids []string
func (_e *PartService_Expecter) Commit(ctx interface{}, uuids interface{}) *PartService_Commit_Call {
	return &PartService_Commit_Call{Call: _e.mock.On("Commit", ctx, uuids)}
}

func (_c *PartService_Commit_Call) Run(run func(ctx context.Context, uuids []string)) *PartService_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PartService_Commit_Call) Return(err error) *PartService_Commit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PartService_Commit_Call) RunAndReturn(run func(ctx context.Context, uuids []string) error) *PartService_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type PartService
func (_mock *PartService) Get(ctx context.Context, uuid string) (model.Part, error) {
	ret := _mock.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.Part, error)); ok {
		return returnFunc(ctx, uuid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.Part); ok {
		r0 = returnFunc(ctx, uuid)
	} else {
		r0 = ret.Get(0).(model.Part)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PartService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type PartService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *PartService_Expecter) Get(ctx interface{}, uuid interface{}) *PartService_Get_Call {
	return &PartService_Get_Call{Call: _e.mock.On("Get", ctx, uuid)}
}

func (_c *PartService_Get_Call) Run(run func(ctx context.Context, uuid string)) *PartService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PartService_Get_Call) Return(part model.Part, err error) *PartService_Get_Call {
	_c.Call.Return(part, err)
	return _c
}

func (_c *PartService_Get_Call) RunAndReturn(run func(ctx context.Context, uuid string) (model.Part, error)) *PartService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type PartService
func (_mock *PartService) List(ctx context.Context, filter valueobject.PartFilter) ([]model.Part, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobject.PartFilter) ([]model.Part, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, valueobject.PartFilter) []model.Part); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, valueobject.PartFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PartService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type PartService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter valueobject.PartFilter
func (_e *PartService_Expecter) List(ctx interface{}, filter interface{}) *PartService_List_Call {
	return &PartService_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *PartService_List_Call) Run(run func(ctx context.Context, filter valueobject.PartFilter)) *PartService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 valueobject.PartFilter
		if args[1] != nil {
			arg1 = args[1].(valueobject.PartFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PartService_List_Call) Return(parts []model.Part, err error) *PartService_List_Call {
	_c.Call.Return(parts, err)
	return _c
}

func (_c *PartService_List_Call) RunAndReturn(run func(ctx context.Context, filter valueobject.PartFilter) ([]model.Part, error)) *PartService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Release provides a mock function for the type PartService
func (_mock *PartService) Release(ctx context.Context, uuids []string) error {
	ret := _mock.Called(ctx, uuids)

	if len(ret) == 0 {
		panic("no return value specified for Release")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = returnFunc(ctx, uuids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PartService_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type PartService_Release_Call struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
//   - ctx context.Context
//   - uuids []string
func (_e *PartService_Expecter) Release(ctx interface{}, uuids interface{}) *PartService_Release_Call {
	return &PartService_Release_Call{Call: _e.mock.On("Release", ctx, uuids)}
}

func (_c *PartService_Release_Call) Run(run func(ctx context.Context, uuids []string)) *PartService_Release_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PartService_Release_Call) Return(err error) *PartService_Release_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PartService_Release_Call) RunAndReturn(run func(ctx context.Context, uuids []string) error) *PartService_Release_Call {
	_c.Call.Return(run)
	return _c
}

// Reserve provides a mock function for the type PartService
func (_mock *PartService) Reserve(ctx context.Context, uuids []string) error {
	ret := _mock.Called(ctx, uuids)

	if len(ret) == 0 {
		panic("no return value specified for Reserve")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = returnFunc(ctx, uuids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PartService_Reserve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reserve'
type PartService_Reserve_Call struct {
	*mock.Call
}

// Reserve is a helper method to define mock.On call
//   - ctx context.Context
//   - uuids []string
func (_e *PartService_Expecter) Reserve(ctx interface{}, uuids interface{}) *PartService_Reserve_Call {
	return &PartService_Reserve_Call{Call: _e.mock.On("Reserve", ctx, uuids)}
}

func (_c *PartService_Reserve_Call) Run(run func(ctx context.Context, uuids []string)) *PartService_Reserve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PartService_Reserve_Call) Return(err error) *PartService_Reserve_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PartService_Reserve_Call) RunAndReturn(run func(ctx context.Context, uuids []string) error) *PartService_Reserve_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateCompatibility provides a mock function for the type PartService
func (_mock *PartService) ValidateCompatibility(ctx context.Context, slots model.ShipSlots) error {
	ret := _mock.Called(ctx, slots)

	if len(ret) == 0 {
		panic("no return value specified for ValidateCompatibility")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ShipSlots) error); ok {
		r0 = returnFunc(ctx, slots)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PartService_ValidateCompatibility_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateCompatibility'
type PartService_ValidateCompatibility_Call struct {
	*mock.Call
}

// ValidateCompatibility is a helper method to define mock.On call
//   - ctx context.Context
//   - slots model.ShipSlots
func (_e *PartService_Expecter) ValidateCompatibility(ctx interface{}, slots interface{}) *PartService_ValidateCompatibility_Call {
	return &PartService_ValidateCompatibility_Call{Call: _e.mock.On("ValidateCompatibility", ctx, slots)}
}

func (_c *PartService_ValidateCompatibility_Call) Run(run func(ctx context.Context, slots model.ShipSlots)) *PartService_ValidateCompatibility_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.ShipSlots
		if args[1] != nil {
			arg1 = args[1].(model.ShipSlots)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PartService_ValidateCompatibility_Call) Return(err error) *PartService_ValidateCompatibility_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PartService_ValidateCompatibility_Call) RunAndReturn(run func(ctx context.Context, slots model.ShipSlots) error) *PartService_ValidateCompatibility_Call {
	_c.Call.Return(run)
	return _c
}
