stage: "development"

kafka:
  brokers:
    - "localhost:9092"

order_paid_consumer:
  topic: "order.paid"
  group: "assembly-service"

ship_assembled_producer:
  topic: "ship.assembled"

shutdown_config:
  shutdown_timeout: "10s"

logger:
  level: "info"

otel:
  endpoint: "localhost:4317"
  service_name: "assembly-service"
