// Code generated for FOCCms service
// © FOCCms 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/FOCCms/go-microservices-course/assembly/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewAssemblyProducerService creates a new instance of AssemblyProducerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAssemblyProducerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AssemblyProducerService {
	mock := &AssemblyProducerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AssemblyProducerService is an autogenerated mock type for the AssemblyProducerService type
type AssemblyProducerService struct {
	mock.Mock
}

type AssemblyProducerService_Expecter struct {
	mock *mock.Mock
}

func (_m *AssemblyProducerService) EXPECT() *AssemblyProducerService_Expecter {
	return &AssemblyProducerService_Expecter{mock: &_m.Mock}
}

// ProduceShipAssembled provides a mock function for the type AssemblyProducerService
func (_mock *AssemblyProducerService) ProduceShipAssembled(ctx context.Context, event model.ShipAssembledEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for ProduceShipAssembled")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ShipAssembledEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AssemblyProducerService_ProduceShipAssembled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProduceShipAssembled'
type AssemblyProducerService_ProduceShipAssembled_Call struct {
	*mock.Call
}

// ProduceShipAssembled is a helper method to define mock.On call
//   - ctx context.Context
//   - event model.ShipAssembledEvent
func (_e *AssemblyProducerService_Expecter) ProduceShipAssembled(ctx interface{}, event interface{}) *AssemblyProducerService_ProduceShipAssembled_Call {
	return &AssemblyProducerService_ProduceShipAssembled_Call{Call: _e.mock.On("ProduceShipAssembled", ctx, event)}
}

func (_c *AssemblyProducerService_ProduceShipAssembled_Call) Run(run func(ctx context.Context, event model.ShipAssembledEvent)) *AssemblyProducerService_ProduceShipAssembled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.ShipAssembledEvent
		if args[1] != nil {
			arg1 = args[1].(model.ShipAssembledEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AssemblyProducerService_ProduceShipAssembled_Call) Return(err error) *AssemblyProducerService_ProduceShipAssembled_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AssemblyProducerService_ProduceShipAssembled_Call) RunAndReturn(run func(ctx context.Context, event model.ShipAssembledEvent) error) *AssemblyProducerService_ProduceShipAssembled_Call {
	_c.Call.Return(run)
	return _c
}
