// Code generated for FOCCms service
// © FOCCms 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/FOCCms/go-microservices-course/inventory/internal/model/entity"
	"github.com/FOCCms/go-microservices-course/inventory/internal/repository/record"
	mock "github.com/stretchr/testify/mock"
)

// NewPartRepository creates a new instance of PartRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPartRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PartRepository {
	mock := &PartRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PartRepository is an autogenerated mock type for the PartRepository type
type PartRepository struct {
	mock.Mock
}

type PartRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PartRepository) EXPECT() *PartRepository_Expecter {
	return &PartRepository_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function for the type PartRepository
func (_mock *PartRepository) Commit(ctx context.Context, uuids []string) error {
	ret := _mock.Called(ctx, uuids)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = returnFunc(ctx, uuids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PartRepository_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type PartRepository_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
//   - uuids []string
func (_e *PartRepository_Expecter) Commit(ctx interface{}, uuids interface{}) *PartRepository_Commit_Call {
	return &PartRepository_Commit_Call{Call: _e.mock.On("Commit", ctx, uuids)}
}

func (_c *PartRepository_Commit_Call) Run(run func(ctx context.Context, uuids []string)) *PartRepository_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PartRepository_Commit_Call) Return(err error) *PartRepository_Commit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PartRepository_Commit_Call) RunAndReturn(run func(ctx context.Context, uuids []string) error) *PartRepository_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type PartRepository
func (_mock *PartRepository) Get(ctx context.Context, id string) (model.Part, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.Part, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.Part); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Part)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PartRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type PartRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *PartRepository_Expecter) Get(ctx interface{}, id interface{}) *PartRepository_Get_Call {
	return &PartRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *PartRepository_Get_Call) Run(run func(ctx context.Context, id string)) *PartRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PartRepository_Get_Call) Return(part model.Part, err error) *PartRepository_Get_Call {
	_c.Call.Return(part, err)
	return _c
}

func (_c *PartRepository_Get_Call) RunAndReturn(run func(ctx context.Context, id string) (model.Part, error)) *PartRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type PartRepository
func (_mock *PartRepository) List(ctx context.Context, filter record.PartFilter) ([]model.Part, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, record.PartFilter) ([]model.Part, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, record.PartFilter) []model.Part); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, record.PartFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PartRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type PartRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter record.PartFilter
func (_e *PartRepository_Expecter) List(ctx interface{}, filter interface{}) *PartRepository_List_Call {
	return &PartRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *PartRepository_List_Call) Run(run func(ctx context.Context, filter record.PartFilter)) *PartRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 record.PartFilter
		if args[1] != nil {
			arg1 = args[1].(record.PartFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PartRepository_List_Call) Return(parts []model.Part, err error) *PartRepository_List_Call {
	_c.Call.Return(parts, err)
	return _c
}

func (_c *PartRepository_List_Call) RunAndReturn(run func(ctx context.Context, filter record.PartFilter) ([]model.Part, error)) *PartRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListForUpdate provides a mock function for the type PartRepository
func (_mock *PartRepository) ListForUpdate(ctx context.Context, filter record.PartFilter) ([]model.Part, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListForUpdate")
	}

	var r0 []model.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, record.PartFilter) ([]model.Part, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, record.PartFilter) []model.Part); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, record.PartFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PartRepository_ListForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListForUpdate'
type PartRepository_ListForUpdate_Call struct {
	*mock.Call
}

// ListForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - filter record.PartFilter
func (_e *PartRepository_Expecter) ListForUpdate(ctx interface{}, filter interface{}) *PartRepository_ListForUpdate_Call {
	return &PartRepository_ListForUpdate_Call{Call: _e.mock.On("ListForUpdate", ctx, filter)}
}

func (_c *PartRepository_ListForUpdate_Call) Run(run func(ctx context.Context, filter record.PartFilter)) *PartRepository_ListForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 record.PartFilter
		if args[1] != nil {
			arg1 = args[1].(record.PartFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PartRepository_ListForUpdate_Call) Return(parts []model.Part, err error) *PartRepository_ListForUpdate_Call {
	_c.Call.Return(parts, err)
	return _c
}

func (_c *PartRepository_ListForUpdate_Call) RunAndReturn(run func(ctx context.Context, filter record.PartFilter) ([]model.Part, error)) *PartRepository_ListForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateReservationsBatch provides a mock function for the type PartRepository
func (_mock *PartRepository) UpdateReservationsBatch(ctx context.Context, parts []model.Part) error {
	ret := _mock.Called(ctx, parts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateReservationsBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []model.Part) error); ok {
		r0 = returnFunc(ctx, parts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PartRepository_UpdateReservationsBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateReservationsBatch'
type PartRepository_UpdateReservationsBatch_Call struct {
	*mock.Call
}

// UpdateReservationsBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - parts []model.Part
func (_e *PartRepository_Expecter) UpdateReservationsBatch(ctx interface{}, parts interface{}) *PartRepository_UpdateReservationsBatch_Call {
	return &PartRepository_UpdateReservationsBatch_Call{Call: _e.mock.On("UpdateReservationsBatch", ctx, parts)}
}

func (_c *PartRepository_UpdateReservationsBatch_Call) Run(run func(ctx context.Context, parts []model.Part)) *PartRepository_UpdateReservationsBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []model.Part
		if args[1] != nil {
			arg1 = args[1].([]model.Part)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PartRepository_UpdateReservationsBatch_Call) Return(err error) *PartRepository_UpdateReservationsBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PartRepository_UpdateReservationsBatch_Call) RunAndReturn(run func(ctx context.Context, parts []model.Part) error) *PartRepository_UpdateReservationsBatch_Call {
	_c.Call.Return(run)
	return _c
}
