// Code generated for FOCCms service
// © FOCCms 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/FOCCms/go-microservices-course/order/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewOrderItemRepository creates a new instance of OrderItemRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderItemRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderItemRepository {
	mock := &OrderItemRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OrderItemRepository is an autogenerated mock type for the OrderItemRepository type
type OrderItemRepository struct {
	mock.Mock
}

type OrderItemRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderItemRepository) EXPECT() *OrderItemRepository_Expecter {
	return &OrderItemRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type OrderItemRepository
func (_mock *OrderItemRepository) Create(ctx context.Context, items []model.OrderItem) error {
	ret := _mock.Called(ctx, items)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []model.OrderItem) error); ok {
		r0 = returnFunc(ctx, items)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OrderItemRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type OrderItemRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - items []model.OrderItem
func (_e *OrderItemRepository_Expecter) Create(ctx interface{}, items interface{}) *OrderItemRepository_Create_Call {
	return &OrderItemRepository_Create_Call{Call: _e.mock.On("Create", ctx, items)}
}

func (_c *OrderItemRepository_Create_Call) Run(run func(ctx context.Context, items []model.OrderItem)) *OrderItemRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []model.OrderItem
		if args[1] != nil {
			arg1 = args[1].([]model.OrderItem)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderItemRepository_Create_Call) Return(err error) *OrderItemRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OrderItemRepository_Create_Call) RunAndReturn(run func(ctx context.Context, items []model.OrderItem) error) *OrderItemRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}
