name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26"

      - name: Create go.work
        run: go work init ./order ./inventory ./payment ./shared

      # Устанавливаем task
      - name: Install Task
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ./bin

      # Запускаем проверки
      - name: Format Check
        run: ./bin/task format

      - name: Lint
        run: ./bin/task ci:lint

      - name: API Tests
        run: ./bin/task test:api
